review of the composite char bar definition
netdata/learn pull request #1064
Opened 2022-06-17 16:14 UTC by hugovalente-pm

The docs were updated due to the work completed and being done on:
* [Feat]: Structure the composite chart bar in a way as if it was being explained in written English [#432](https://github.com/netdata/netdata-cloud/issues/432)
* [Feat]: Allow the definition of the aggregation function over time on composite charts bar [#433](https://github.com/netdata/netdata-cloud/issues/433

As from previous conversations, on the places where the intervention happened images were removed.

For further information on composite charts please refer to https://github.com/netdata/docs/blob/master/product/composite-charts/composite_charts_behind_the_scnenes.md

2022-06-17 16:29 UTC, jlbriston commented on docs/cloud/visualize/overview.md
> +dropdown displays a instance name and the associated node's hostname.
```suggestion
dropdown displays an instance name and the associated node's hostname.
```

2022-06-17 16:33 UTC, jlbriston commented on docs/cloud/visualize/overview.md
> +Each composite chart has a definition bar to provide information about the:
```suggestion
Each composite chart has a definition bar to provide information about the following:
```

2022-06-17 16:35 UTC, jlbriston commented on docs/cloud/visualize/overview.md
> +A composite chart group by _instance_ visualizes each instance of one software or hardware on a node and displays these as a separate dimension. By grouping the
```suggestion
A composite chart grouped by _instance_ visualizes each instance of one software or hardware on a node and displays these as a separate dimension. By grouping the
```

2022-06-17 16:49 UTC, DShreve2 requested changes

2022-06-17 16:49 UTC, DShreve2 commented on docs/cloud/visualize/overview.md
> +The default is by _dimension_, so that each line/area in the visualization is the aggregation of a single dimension.
```suggestion
The default option is by _dimension_, so that each line/area in the visualization is the aggregation of a single dimension.
```

2022-06-17 16:49 UTC, DShreve2 commented on docs/cloud/visualize/overview.md
> +A composite chart grouped by _node_ visualizes a single metric across contributing nodes. If the composite chart has 5
```suggestion
A composite chart grouped by _node_ visualizes a single metric across contributing nodes. If the composite chart has five
```

2022-06-17 16:49 UTC, DShreve2 commented on docs/cloud/visualize/overview.md
> +contributing nodes, there will be 5 lines/areas. This is typically an absolute value of the sum of the dimensions over each node but there
```suggestion
contributing nodes, there will be five lines/areas. This is typically an absolute value of the sum of the dimensions over each node but there
```

2022-06-17 16:49 UTC, DShreve2 commented on docs/cloud/visualize/overview.md
> +are some opinionated-but-valuable exceptions where a specific dimension is selected.
Do we need to explain what "opinionated-but-valuable" exceptions means? Could we say but "but there are some exceptions where selecting a specific dimension might offer value."?

2022-06-17 16:49 UTC, DShreve2 commented on docs/cloud/visualize/overview.md
> +* aggregate function over time to be applied if one point in the chart consists of multiple data points aggregated
We capitalize the list below. I saw capitalize both lists?

2022-06-17 21:32 UTC, hugovalente-pm commented on docs/cloud/visualize/overview.md
> +are some opinionated-but-valuable exceptions where a specific dimension is selected.
This was something I had picked from Joel on another place and we didn't explain that, if we want to do it we will need to explain on the other place as well

2022-06-18 16:30 UTC, hugovalente-pm commented on docs/cloud/visualize/overview.md
> +* aggregate function over time to be applied if one point in the chart consists of multiple data points aggregated
changes applied

2022-06-21 13:16 UTC, jlbriston commented on docs/cloud/visualize/overview.md
> +For more details on each you can refer to our Agent's HTTP API details on [Data Queries - Data Grouping](/docs/agent/web/api/queries#data-grouping).
```suggestion
For more details on each, you can refer to our Agent's HTTP API details on [Data Queries - Data Grouping](/docs/agent/web/api/queries#data-grouping).
```

2022-06-21 14:06 UTC, DShreve2 approved these changes

2022-06-21 14:08 UTC, merged