Updating Netdata cloud docs
netdata/learn pull request #1083
Opened 2022-06-29 10:00 UTC by tkatsoulas

Our current docs a bit outdated, starting an effort to bring them up to speed.

Signed-off-by: Tasos Katsoulas <tasos@netdata.cloud>

2022-06-29 17:00 UTC, DShreve2 requested changes

2022-06-29 17:00 UTC, DShreve2 commented on docs/cloud/war-rooms.md
> +the **🗑** icon. Removing a node from a War Room does not remove it from your Space.
The last sentence might be important enough to put as a note.

2022-06-29 17:11 UTC, tkatsoulas commented on docs/cloud/spaces.md
> +:::caution
Made it a note, good catch

2022-06-29 17:11 UTC, tkatsoulas commented on docs/cloud/war-rooms.md
> +the **🗑** icon. Removing a node from a War Room does not remove it from your Space.
made it an info admonition

2022-06-29 17:20 UTC, tkatsoulas commented on docs/cloud/war-rooms.md
> +the **🗑** icon.
This icon need replacement, but I can't find it (I think it's a react svg)

2022-06-29 19:46 UTC, shyamvalsan commented on docs/cloud/spaces.md
> +If you aren't invited to Netdata Cloud by another user, you'll create your first Space during the onboarding process
Is this true? Isn't your first Space auto created for you?

2022-06-29 19:47 UTC, shyamvalsan commented on docs/cloud/spaces.md
> +Room.
Maybe we should just lose the "in each War Room." here or at least link to the war room section since it is the first mention of it in this page.

2022-06-29 19:48 UTC, shyamvalsan commented on docs/cloud/spaces.md
> +For startups, small-mid-size businesses, or focused independent teams, we recommend sticking to a single Space so
I'd rather say something like "For smaller teams we recommend sticking to a single Space"

2022-06-29 19:51 UTC, shyamvalsan requested changes
I've left a few comments - but looks good overall

2022-06-30 09:47 UTC, tkatsoulas commented on docs/cloud/spaces.md
> +If you aren't invited to Netdata Cloud by another user, you'll create your first Space during the onboarding process
no it's not, just tested it (couldn't recall what I have done when I created my first acc, that's why I didn't update this info)

2022-06-30 12:02 UTC, shyamvalsan approved these changes

2022-06-30 15:02 UTC, DShreve2 approved these changes

2022-06-30 15:05 UTC, merged