Mc doc improvements
netdata/learn pull request #1123
Opened 2022-07-29 11:33 UTC by andrewm4894

- Add section about options.
- Add usage tips section.

2022-07-29 11:35 UTC, andrewm4894 commented
![image](https://user-images.githubusercontent.com/2178292/181750606-4dd5f216-ec83-46c9-92f8-b307264bfd9a.png)

2022-07-29 11:38 UTC, andrewm4894 commented
![image](https://user-images.githubusercontent.com/2178292/181751182-25e0890d-a5f4-4799-9936-1523603cf97d.png)

2022-07-29 11:45 UTC, andrewm4894 commented on docs/cloud/insights/metric-correlations.md
> +- `Volume` -  A heuristic measure based on the percentage change in averages between highlighted window and baseline, with various edges cases sensibly controlled for. You can explore our implementat
@ktsaou feel free to update or change this as you know most about this method.

2022-07-29 11:46 UTC, andrewm4894 commented on docs/cloud/insights/metric-correlations.md
> +## Usage tips!
@cakrit fyi - added a usage tips section.

2022-07-29 12:19 UTC, hugovalente-pm requested changes
The generic feedback is about adding the screenshoots, since we were trying to move away from having them on docs

2022-07-29 12:19 UTC, hugovalente-pm commented on docs/cloud/insights/metric-correlations.md
> +![The Metric Correlations button in a single-node dashboard](https://user-images.githubusercontent.com/2178292/181750606-4dd5f216-ec83-46c9-92f8-b307264bfd9a.png)
I know visuals are always helpful but I think @DShreve2 was trying to move away from having images/GIFs on the docs.
The main reason for that is that with any change that happens on the UI it would almost for sure trigger a docs review

2022-07-29 12:19 UTC, hugovalente-pm commented on docs/cloud/insights/metric-correlations.md
> +Press the **Find Correlations** button to start up the correlations service, the button is only enabled when a valid timeframe is selected (at least 15 seconds). Once pressed, the service will score
```suggestion
Press the **Find Correlations** button to start up the correlations process, the button is only enabled when a valid timeframe is selected (at least 15 seconds). Once pressed, the process will score all available metrics on your node and returns a filtered version of the Netdata dashboard. Now, you'll see only those metrics that have changed the most between a baseline window and the highlighted window you have selected.
```

was thinking that service was mostly implying our correlations service that we had in Cloud, but also not so sure if `process` is the bet alternative

2022-07-29 12:19 UTC, hugovalente-pm commented on docs/cloud/insights/metric-correlations.md
> +Their are two algorithms available that aim to score metrics based on how much they have changed between the baseline and highlight windows.
```suggestion
There are two algorithms available that aim to score metrics based on how much they have changed between the baseline and highlight windows.
```

2022-07-29 12:19 UTC, hugovalente-pm commented on docs/cloud/insights/metric-correlations.md
> +Behind the scenes Netdata will aggregate the raw data as needed such that arbitrary window lengths can be selected for MC. By default Netdata will just `Average` raw data when needed as part of pre-p
```suggestion
Behind the scenes, Netdata will aggregate the raw data as needed such that arbitrary window lengths can be selected for MC. By default, Netdata will just `Average` raw data when needed as part of pre-processing. However other aggregations like `Median`, `Min`, `Max`, `Stddev` are also possible.
```

2022-07-29 12:19 UTC, hugovalente-pm commented on docs/cloud/insights/metric-correlations.md
> +Netdata is different than typical observability agents in that in addition to just collecting raw metric values, it will by default also assign an "[Anomaly Bit](/docs/agent/ml#anomaly-bit)" related
```suggestion
Netdata is different than typical observability agents since, in addition to just collecting raw metric values, it will by default also assign an "[Anomaly Bit](/docs/agent/ml#anomaly-bit)" related to each collected metric each second. This bit will be 0 for "normal" and 1 for "anomalous". This means that each metric also natively has an "[Anomaly Rate](/docs/agent/ml#anomaly-rate)" associated with it and, as such, MC can be run against the raw metric values or their corresponding anomaly rates.
```

2022-07-29 12:19 UTC, hugovalente-pm commented on docs/cloud/insights/metric-correlations.md
> +- By default Netdata uses the `KS2` algorithm which is a tried and tested method for change detection in a lot of domains. The [Wikipedia](https://en.wikipedia.org/wiki/Kolmogorov%E2%80%93Smirnov_tes
```suggestion
- By default, Netdata uses the `KS2` algorithm which is a tried and tested method for change detection in a lot of domains. The [Wikipedia](https://en.wikipedia.org/wiki/Kolmogorov%E2%80%93Smirnov_test) article gives a good overview of how this works. Basically, it is comparing, for each metric, its cumulative distribution in the highlight window with its cumulative distribution in the baseline window. The statistical test then seeks to quantify the extent to which we can say these two distributions look similar enough to be considered the same or not.  
```

2022-07-29 12:31 UTC, andrewm4894 commented on docs/cloud/insights/metric-correlations.md
> +![The Metric Correlations button in a single-node dashboard](https://user-images.githubusercontent.com/2178292/181750606-4dd5f216-ec83-46c9-92f8-b307264bfd9a.png)
yeah i just could not leave the old one that is there in there as is :) 

I kinda think its better to have images in the docs to make the docs better (imagine trying to explain how to trgigger MC from toolbar in text lol) even if they might end a little outdated. If that happens it means we are buidling stuff and not also thinking about the docs which i think is bad. 

We change something then just updating the relevant docs shoudl also include the images.

So i see both sides but on balance i dont think just not including images is really a solution.

@DShreve2 i guess something to put into the mix as part of the ongoing docs work maybe. 

I think maybe keeping images to a minimum or where 100% needed maybe could be a good balance perhaps?

2022-07-29 12:32 UTC, andrewm4894 commented
thanks @hugovalente-pm for catching some of those!

2022-07-29 13:11 UTC, shyamvalsan commented on docs/cloud/insights/metric-correlations.md
> +![The Metric Correlations button in a single-node dashboard](https://user-images.githubusercontent.com/2178292/181750606-4dd5f216-ec83-46c9-92f8-b307264bfd9a.png)
I think a simple image to point out how to trigger the functionality would definitely be useful.

2022-07-29 13:13 UTC, shyamvalsan commented on docs/cloud/insights/metric-correlations.md
> +To start correlating metrics, click the **Metric Correlations** button, then hold the `Alt` key (or `⌘` on macOS) and click-and-drag a selection of metrics on a single chart. The selected timeframe n
works best? should this just say work. I think we show a message asking the user to select at least 15 seconds if they don't.

2022-07-29 13:14 UTC, shyamvalsan commented on docs/cloud/insights/metric-correlations.md
> +The menu then displays information about the selected area and reference baseline. Metric Correlations uses the reference baseline to discover which additional metrics are most closely connected to t
Is it self evident what a "reference baseline" is to a user who reads this?

2022-07-29 13:16 UTC, shyamvalsan commented on docs/cloud/insights/metric-correlations.md
> +So by when you first run MC it will use the most sensible and general defaults. But you can also then vary any of the below options to explore further.
remove "by"

2022-07-29 14:30 UTC, DShreve2 approved these changes

2022-07-29 19:55 UTC, andrewm4894 commented on docs/cloud/insights/metric-correlations.md
> +To start correlating metrics, click the **Metric Correlations** button, then hold the `Alt` key (or `⌘` on macOS) and click-and-drag a selection of metrics on a single chart. The selected timeframe n
correct

2022-07-29 19:55 UTC, andrewm4894 commented on docs/cloud/insights/metric-correlations.md
> +The menu then displays information about the selected area and reference baseline. Metric Correlations uses the reference baseline to discover which additional metrics are most closely connected to t
no - feel free to make suggestions i can just press a button in here to commit :)

2022-07-29 19:56 UTC, andrewm4894 commented on docs/cloud/insights/metric-correlations.md
> +So by when you first run MC it will use the most sensible and general defaults. But you can also then vary any of the below options to explore further.
make suggestion instead of comment :)

2022-08-01 10:11 UTC, hugovalente-pm commented on docs/cloud/insights/metric-correlations.md
> +![The Metric Correlations button in a single-node dashboard](https://user-images.githubusercontent.com/2178292/181750606-4dd5f216-ec83-46c9-92f8-b307264bfd9a.png)
probably a .gif here would make more sense then, no?

2022-08-01 14:08 UTC, cakrit commented on docs/cloud/insights/metric-correlations.md
> +- `Volume` -  A heuristic measure based on the percentage change in averages between highlighted window and baseline, with various edges cases sensibly controlled for. You can explore our implementat
"edges cases" -> "edge cases"

2022-08-01 14:19 UTC, cakrit commented on docs/cloud/insights/metric-correlations.md
> +## Usage tips!
I'd restructure as follows and add charts showing what we're talking about.

- Use the `Volume` algorithm for metrics with a lot of gaps (e.g. request latency when there are few requests), otherwise stick with `KS2`
  - By default, Netdata uses the `KS2` algorithm which is a tried and tested method for change detection in a lot of domains. The [Wikipedia](https://en.wikipedia.org/wiki/Kolmogorov%E2%80%93Smirnov_test) article gives a good overview of how this works. Basically, it is comparing, for each metric, its cumulative distribution in the highlight window with its cumulative distribution in the baseline window. The statistical test then seeks to quantify the extent to which we can say these two distributions look similar enough to be considered the same or not. The `Volume` algorithm is a bit more simple than `KS2` in that it basically compares (with some edge cases sensibly handled) the average value of the metric across baseline and highlight and looks at the percentage change. Often both `KS2` and `Volume` will have significant agreement and return similar metrics.
  - `Volume` might favour picking up more sparse metrics that were relatively flat and then came to life with some spikes (or vice versa). This is because for such metrics that just don't have that many different values in them, it is impossible to construct cumulative distribution's that can then be compared. So `Volume` might be useful in spotting examples of metrics turning on or off. [ADD EXAMPLE CHART BELOW HERE]
  - `KS2` since it relies on the full distribution might be better at highlighting more complex changes that `Volume` is unable to capture. For example a change in the variation of a metric might be picked up easily by `KS2` but missed (or just much lower scored) by `Volume` since the averages might remain not all that different between baseline and highlight even if their variance has changed a lot. [ADD EXAMPLE CHART BELOW HERE]
- Use `Volume` and `Anomaly Rate` together to ask what metrics have turned most anomalous from baseline to highlighted window. You can expand the embedded anomaly rate chart once you have results to see this more clearly. [ADD EXAMPLE CHART BELOW HERE]

2022-08-02 08:58 UTC, andrewm4894 commented on docs/cloud/insights/metric-correlations.md
> +## Usage tips!
i like this and idea of showing a sort of illustrative example chart.

2022-08-02 09:04 UTC, andrewm4894 commented
example image where `Volume` picked up fact that network traffic came to life.

![image](https://user-images.githubusercontent.com/2178292/182336924-d02fd3d3-7f09-41da-9cfc-809d01396d9d.png)

2022-08-02 09:11 UTC, andrewm4894 commented
example image where `KS2` would be better at picking up a more complex distributional change

![image](https://user-images.githubusercontent.com/2178292/182338289-59b61e6b-089d-431c-bc8e-bd19ba6ad5a5.png)

2022-08-02 09:13 UTC, andrewm4894 commented
using volume and anomaly rate together 
![image](https://user-images.githubusercontent.com/2178292/182338666-6d19fa92-89d3-4d61-804c-8f10982114f5.png)

2022-08-02 09:18 UTC, andrewm4894 commented on docs/cloud/insights/metric-correlations.md
> +## Usage tips!
done - i think it is better with the illustrative charts too.

2022-08-02 09:21 UTC, andrewm4894 commented on docs/cloud/insights/metric-correlations.md
> +To start correlating metrics, click the **Metric Correlations** button, then hold the `Alt` key (or `⌘` on macOS) and click-and-drag a selection of metrics on a single chart. The selected timeframe n
done

2022-08-02 09:25 UTC, andrewm4894 commented on docs/cloud/insights/metric-correlations.md
> +The menu then displays information about the selected area and reference baseline. Metric Correlations uses the reference baseline to discover which additional metrics are most closely connected to t
added a sentence for this

2022-08-03 14:42 UTC, merged