Update the information inside README.md
netdata/learn pull request #1484
Opened 2023-03-10 08:41 UTC by Ancairon

Related to https://github.com/netdata/learn/issues/1469

This PR updates the `README.md`, removing old sections, ensuring everything is up-to-date and checking spelling and syntax.

2023-03-13 13:27 UTC, cakrit requested changes
Step 2 fails for me with 

```
cakrit@DESKTOP-C7OKV71:/mnt/c/Users/cakri/github/learn$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
```

yarn version: 0.32+git

2023-03-13 13:45 UTC, Ancairon commented
@cakrit Did you install yarn from the prerequisites link? I see that the latest version is `1.22.19`, and yours is `0.32+git`

2023-03-14 07:04 UTC, Ancairon commented
I am going to put the latest offered from yarn as the least required version, as there isn't another version limit somewhere, latest works

2023-03-14 16:39 UTC, cakrit approved these changes

2023-03-14 16:39 UTC, merged