sign up to sign in CTA review
netdata/learn pull request #624
Opened 2021-07-13 09:42 UTC by hugovalente-pm

This PR is still not updated with the latest version of the "Verify email!" e-mail screenshot. Once that is available I'll update it.
Putting the PR to trigger the review

2021-07-19 18:23 UTC, manos-saratsis commented on docs/cloud/get-started.mdx
> +Get started by signing in to Netdata Cloud. Read the [sign in](/docs/cloud/manage/sign-in) doc for details on the
@hugovalente-pm "Sign in" without "to Netdata Cloud" is preferred.

2021-07-20 08:02 UTC, hugovalente-pm commented on docs/cloud/get-started.mdx
> +Get started by signing in to Netdata Cloud. Read the [sign in](/docs/cloud/manage/sign-in) doc for details on the
Just pushed a fix for this on this file and on `docs/cloud/manage/sign-in.md`. please review.

2021-07-21 15:33 UTC, manos-saratsis approved these changes

2021-07-26 14:37 UTC, OdysLam requested changes

2021-07-26 14:37 UTC, OdysLam commented on docs/cloud/manage/sign-in.md
> +Netdata Cloud not store passwords and does not support password resets. All of our sign in methods do not
```suggestion
Netdata Cloud does not store passwords and does not support password resets. All of our sign in methods do not
```

2021-07-26 14:37 UTC, OdysLam commented on docs/cloud/manage/sign-in.md
> +Relax! Sign in and we will create one for you!
Not sure what you mean by this. We should change the tone of this phrase.

2021-07-26 14:57 UTC, hugovalente-pm commented on docs/cloud/manage/sign-in.md
> +Relax! Sign in and we will create one for you!
@OdysLam was trying to put this in-line to the tone we have on our app for the sign in screen, please see printscreen below

![image](https://user-images.githubusercontent.com/82235632/127010901-42307639-e05e-478c-ab43-f5d7078e995a.png)

2021-07-27 15:07 UTC, manos-saratsis approved these changes

2021-07-29 09:15 UTC, hugovalente-pm commented on docs/cloud/manage/sign-in.md
> +Relax! Sign in and we will create one for you!
@OdysLam @manos-saratsis pushed a change to this text to review the tone of voice.

2021-08-02 15:59 UTC, OdysLam approved these changes

2021-08-02 15:59 UTC, merged