New Beta Architecture Request Page
netdata/learn pull request #775
Opened 2021-11-15 16:39 UTC by DShreve2

2021-11-15 17:10 UTC, DShreve2 commented on docs/cloud/Beta Architecture/new-architecture.md
> +We would like to give you the opportunity to be among the first users to try our new Cloud architecture and provide feedback.
Got it.

2021-11-15 17:17 UTC, georgiats requested changes
I'm sorry I provided you with the wrong link. This is the [correct Discord link](https://discord.gg/kUk3nCmbtx) for someone to join our channel.

2021-11-15 17:23 UTC, georgiats commented on docs/cloud/Beta Architecture/new-architecture.md
> +To enable enable the new architecture, first ensure that you have installed the latest Netdata version following
Do you think it'd be possible to also provide the number of the latest version so that the users are sure they have the right one?

2021-11-15 17:39 UTC, DShreve2 commented on docs/cloud/Beta Architecture/new-architecture.md
> +To enable enable the new architecture, first ensure that you have installed the latest Netdata version following
Do we want to use v.1.31?

2021-11-15 18:17 UTC, jlbriston requested changes

2021-11-15 18:17 UTC, jlbriston commented on docs/cloud/Beta Architecture/new-architecture.md
> +  Would you like to be the first try try our new architecture and provide feedback?
```suggestion
  Would you like to be the first to try our new architecture and provide feedback? 
```

2021-11-15 18:17 UTC, jlbriston commented on docs/cloud/Beta Architecture/new-architecture.md
> +  This guide will help you sign up for our beta testing group.
```suggestion
  If so, this guide will help you sign up for our beta testing group.
```

2021-11-15 18:17 UTC, jlbriston commented on docs/cloud/Beta Architecture/new-architecture.md
> +- Parent/Child cloud relationships
```suggestion
- Parent/Child Cloud relationships
```

2021-11-15 18:17 UTC, jlbriston commented on docs/cloud/Beta Architecture/new-architecture.md
> +To enable enable the new architecture, first ensure that you have installed the latest Netdata version following
```suggestion
To enable the new architecture, first ensure that you have installed the latest Netdata version following 
```

2021-11-15 18:17 UTC, jlbriston commented on docs/cloud/Beta Architecture/new-architecture.md
> +requesting to be included in our beta testers, and include in the body of the email a list of Space IDs for any spaceyou would like to have
```suggestion
requesting to be included in our beta testers, and include in the body of the email a list of Space IDs for any space you would like to have
```

2021-11-16 16:41 UTC, manos-saratsis commented on docs/cloud/Beta Architecture/new-architecture.md
> +To enable enable the new architecture, first ensure that you have installed the latest Netdata version following
@DShreve2 not all agents on v1.31 are able. @stelfrag do you remember which is the nightly that enabled it?

2021-11-16 18:07 UTC, stelfrag commented on docs/cloud/Beta Architecture/new-architecture.md
> +To enable enable the new architecture, first ensure that you have installed the latest Netdata version following
That would be `v1.31.0-497-nightly`

2021-11-16 18:28 UTC, DShreve2 commented on docs/cloud/Beta Architecture/new-architecture.md
> +To enable enable the new architecture, first ensure that you have installed the latest Netdata version following
"To enable the new architecture, first ensure that you have installed `v1.31.0-497-nightly` following..."

This works?

2021-11-17 15:52 UTC, merged