Updated documentation for charts (cloud)
netdata/learn pull request #787
Opened 2021-11-25 14:58 UTC by kickoke

I updated the topic on charts in the cloud, mainly refining the copy. I also renamed the file from interact-new-charts.md into interact-charts-cloud.md to differentiate between the Agent documentation, which is called interact-charts.mdx
I also updated the links.

2021-11-25 16:24 UTC, hugovalente-pm requested changes
If you just change the stuff on /docs/cloud this is good to go, with the dependency on the agent it would mean we would need to _hold_ the fix on the `new` on the filename until we have the stuff from the Agent merged.

Suggestion just change the `/docs/cloud/visualize/interact-new-charts.md` stuff and on a next PR the filename could be changed

2021-11-25 16:24 UTC, hugovalente-pm commented on docs/dashboard/interact-charts.mdx
> -  - [Netdata Cloud · Interact with new charts](/docs/cloud/visualize/interact-new-charts)
For this specific change we need to do it on the Agent repo, please check [here](https://github.com/netdata/learn#ingest-and-process-documentation-files).

If it is files under /docs/cloud/ and the sidebar that refers to this section this is the right repo, for the others we need to start the update from the Agent repo (netdata/netdata)

2021-11-26 10:10 UTC, kickoke commented on docs/dashboard/interact-charts.mdx
> -  - [Netdata Cloud · Interact with new charts](/docs/cloud/visualize/interact-new-charts)
Changed the filename back to interact-new-charts
I might need to update/ restructure the docs soon, so the naming concern isn't urgent.

2021-11-26 10:12 UTC, kickoke commented
Changed back the filename to interact-new-charts as a quick fix. However, the documentation probably needs restructuring in the future.

2021-11-26 10:16 UTC, hugovalente-pm approved these changes

2021-11-26 10:25 UTC, merged