Create anomaly-advisor.md
netdata/learn pull request #957
Opened 2022-03-28 13:07 UTC by andrewm4894

2022-04-21 09:42 UTC, andrewm4894 commented
adding some images 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/2178292/164427230-53d742de-ccf6-4904-98b5-3ef7e4b08a5c.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/2178292/164427337-a40820d2-8d36-4a94-8dfb-cfd3194941e0.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/2178292/164427592-ab1d0eb1-57e2-4a05-aaeb-da4437a019b1.png">

2022-04-21 09:45 UTC, andrewm4894 commented
<img width="632" alt="image" src="https://user-images.githubusercontent.com/2178292/164428307-6a86989a-611d-47f8-a673-911d509cd954.png">

2022-04-21 09:55 UTC, andrewm4894 commented
<img width="641" alt="image" src="https://user-images.githubusercontent.com/2178292/164430105-f747d1e0-f3cb-4495-a5f7-b7bbb71039ae.png">

2022-04-21 10:12 UTC, andrewm4894 commented
<img width="720" alt="image" src="https://user-images.githubusercontent.com/2178292/164433258-ee7252be-c9b0-48be-9d68-a5addd4ba84d.png">

2022-04-21 13:34 UTC, shyamvalsan commented on docs/cloud/insights/anomaly-advisor.md
> +To enable ML on you Netdata Agent you just need to edit the `[ml]` section in your `netdata.conf` to look something like below.
on "your" agent

2022-04-21 13:38 UTC, shyamvalsan commented on docs/cloud/insights/anomaly-advisor.md
> +The "Anomaly Events Detected" chart (collapsed by default) shows if the anomaly rate per node was sufficiently elevated to trigger a node level anomaly.
Maybe we should add a sentence here, something to the effect of, "Anomaly events appear slightly after the anomaly rate starts to increase in the timeline, since a significant number of metrics in the node need to be anomalous before an anomaly event is triggered."

2022-04-21 13:39 UTC, shyamvalsan commented on docs/cloud/insights/anomaly-advisor.md
> +You can read more detail on how anomaly detection in the netdata agent works in our [agent docs](https://github.com/netdata/netdata/blob/master/ml/README.md).
I think there should be some mention of the elements on the right hand side:
- node filter and info 
- index of anomaly rate/toc

2022-04-21 14:01 UTC, andrewm4894 commented
@shyamvalsan maybe feel free to make commit suggestions

2022-04-21 16:31 UTC, shyamvalsan approved these changes

2022-04-22 14:46 UTC, andrewm4894 commented
@DShreve2 i dont think i have write access to learn so think this would be one you would need to merge.

2022-04-27 13:27 UTC, DShreve2 requested changes

2022-04-27 13:31 UTC, DShreve2 approved these changes

2022-04-27 13:31 UTC, merged